---
title: "About NHS Open Analytics Community"
format: html
---

The NHS Open Analytics Community was formed in 2025 by an enthusiastic group of 
volunteers from across the NHS. The much loved NHS-R and NHS.pycom communities
were merged to allow a stronger voice in support of NHS analysts and data
scientists who care about promoting the use of open code and tools in health and 
care.

We aim to promote best practice and values of transparency, sharing, and
collaboration in the use of health and care data, but we also welcome those who
share our values from the public sector, academia, and the third sector. 

We are coding language-agnostic, but principally provide resources and training
in R and python.

NHS-OA is hosted by [The Strategy Unit](https://www.strategyunitwm.nhs.uk/)
Substack

## How can I get involved?

Whether you are a complete novice at coding or a seasoned professional, a 
senior leader or on day one of your career, the community has something to 
offer you!

📢 Join the conversation over on [Slack](https://nhsoacommunity.slack.com)!

📖 Check out our free online [books](books/index.qmd) and [training materials](training/index.qmd)!

🎪 Come along to one of our [events](events/events.qmd)!

📽️ [Watch](https://www.youtube.com/@NHSOA_Community) our previous conferences, webinars and workshops on all manner of topics!

🪄 [Contribute](https://github.com/nhs-oa-community) to our codebases - including this website!

😎 Join the [committee](mailto: openanalytics.community@nhs.net) and have your say on how we run!

## Statement on open code

NHS Open Analytics (NHS OA) is comprised of analysts, data scientists, and clinicians from across the NHS. As individuals, our members make use of numerous tools and approaches to harness the power and potential of data to support the health of the nation through the work of the NHS.

Open source is a mature movement within technology whereby the code used to produce a computer program, website, or piece of analysis is shared in the interests of collaboration, improvement, and reproducibility.

Within the NHS OA community, we strive to ensure that materials, software, and analytical methods are made freely available to our members and the wider public.

**Why is this important?**

Across the UK, the NHS provides care to the nation. The care provided aims to be comparable regardless of where a patient is treated. In the same way that clinical care is delivered according to national standards, NHS staff also use software and code to report on the performance of clinical services. Historically, while standards of care have sought to be consistent, the methods used to generate reports for the same purposes have not been standardised. This has resulted in duplication of effort and variation in analytical methods, which can introduce inconsistencies and errors in how data are used and interpreted across the NHS.

Open analytical code promotes transparency, trust, and learning across the NHS. By making methods and code openly available, analytical work can be reviewed, challenged, improved, and reproduced by others. This helps to identify errors, share best practice, and build confidence in the statistics and insights used to inform decision-making. As the NHS continues to make greater use of data, advanced analytics, and artificial intelligence, openness in the methods used to generate evidence will be essential to maintaining public trust and ensuring that innovation is delivered safely and consistently.

At NHS OA, we believe in sharing code, establishing standards for analysis, and using consistent methods nationally to report the same statistics. To achieve this, analytical code should be published openly and the reuse of code should be actively encouraged.

The adoption and reuse of open analytical code represent a significant opportunity for the NHS to improve reporting standards, reduce variation in the statistics generated by providers, and free up time for analysts, data scientists, and clinicians to focus on new ways of using data to support the NHS in delivering better care for the nation.
